package com.veylon.save;

import com.veylon.Game;
import com.veylon.world.BlockType;
import com.veylon.world.Chunk;
import com.veylon.world.World;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.DataInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.Base64;
import java.util.HexFormat;
import java.util.Objects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Compatibility evidence produced by the actual 0.2.0 implementation.
 *
 * <p>The fixture was generated from tag {@code v0.2.0}, commit
 * {@code 3aac827e7d55da2a636af1d86b48b69ce3eccd83}, by compiling that archived
 * source in isolation and invoking its {@code SaveSystem.save(Game, Path)}.
 * The same historical run emitted the three expected chunk hashes below. The
 * binary save is Base64-encoded only so the generated bytes can be reviewed as
 * a small text test resource; its decoded SHA-256 is asserted before loading.</p>
 */
class HistoricalV020SaveCompatibilityTest {

    private static final long HISTORICAL_SEED = 1122334455L;
    private static final String FIXTURE_SHA256 =
            "89a95906d40cb992528f6b7415809cf7b1162f65611a1ddcfb9645d243507c17";
    private static final int[][] LEGACY_CHUNKS = {
            {37, -29},
            {-41, 33},
            {80, 80}
    };
    private static final String[] LEGACY_CHUNK_SHA256 = {
            "c0117ecd934153ccb09cc970460c573d6d7e89264526940372da5067fc2933f7",
            "17f917c17fb22590e0fa8111aa9e5e7f15cefa4c0ecc612b6def7fa6c175e3d9",
            "7fceb6079fc42cb687376489708826b9a3ec35bb87afe73df9d27fa8bfd4522c"
    };

    @Test
    void authenticV020SavePinsLegacyGeneratorForFutureChunks(@TempDir Path dir)
            throws Exception {
        byte[] fixture = readFixture();
        assertEquals(FIXTURE_SHA256, sha256(fixture),
                "fixture bytes must remain the output captured from the historical writer");
        try (DataInputStream header = new DataInputStream(
                new java.io.ByteArrayInputStream(fixture))) {
            assertEquals(0x5645594C, header.readInt(), "historical VEYL magic");
            assertEquals(2, header.readInt(), "historical writer format version");
            assertEquals(HISTORICAL_SEED, header.readLong());
        }

        Path save = dir.resolve("historical-v0.2.0.sav");
        Files.write(save, fixture);
        Game game = new Game();

        assertTrue(SaveSystem.load(game, save), "the real 0.2.0 save must migrate");
        assertEquals(1, World.GEN_LEGACY, "legacy generator id is serialized policy");
        assertEquals(World.GEN_LEGACY, game.world.generatorVersion,
                "v2 saves must remain pinned to generator v1");
        assertEquals(HISTORICAL_SEED, game.world.seed);
        assertEquals(73.25f, game.player.health, 0.001f);
        assertEquals(2, game.player.hotbarSel);
        assertEquals(41f, game.faction.trust, 0.001f);
        assertEquals(9, game.faction.foodStock);
        assertEquals(7, game.faction.woodStock);
        assertTrue(game.eventLog.recent(30).contains(
                "Authentic v0.2.0 compatibility fixture"));
        assertTrue(game.world.settlements.isEmpty());

        for (int i = 0; i < LEGACY_CHUNKS.length; i++) {
            int cx = LEGACY_CHUNKS[i][0];
            int cz = LEGACY_CHUNKS[i][1];
            assertNull(game.world.getChunk(cx, cz),
                    "compatibility check must generate a previously unseen chunk");

            Chunk generated = game.world.getOrCreateChunk(cx, cz);
            assertEquals(LEGACY_CHUNK_SHA256[i], sha256(generated),
                    "newly generated terrain must remain byte-identical to v0.2.0 at "
                            + cx + "," + cz);
            assertContainsOnlyV020Blocks(generated);
            assertNull(game.world.settlementAt(cx * Chunk.SX + Chunk.SX / 2,
                    cz * Chunk.SZ + Chunk.SZ / 2),
                    "a migrated v2 world must never plan a v3 settlement");
        }

        assertTrue(game.world.settlements.isEmpty(),
                "generating positive and negative distant regions must not add settlements");
        assertFalse(game.world.loadedChunks().isEmpty());
    }

    private static byte[] readFixture() throws Exception {
        try (InputStream resource = Objects.requireNonNull(
                HistoricalV020SaveCompatibilityTest.class.getResourceAsStream(
                        "/com/veylon/save/v0.2.0-authentic.sav.b64"),
                "historical v0.2.0 fixture")) {
            String encoded = new String(resource.readAllBytes(), StandardCharsets.US_ASCII).trim();
            return Base64.getDecoder().decode(encoded);
        }
    }

    private static String sha256(byte[] bytes) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    }

    private static String sha256(Chunk chunk) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        for (int y = 0; y < Chunk.SY; y++) {
            for (int z = 0; z < Chunk.SZ; z++) {
                for (int x = 0; x < Chunk.SX; x++) {
                    digest.update(chunk.get(x, y, z).id());
                }
            }
        }
        return HexFormat.of().formatHex(digest.digest());
    }

    private static void assertContainsOnlyV020Blocks(Chunk chunk) {
        int lastHistoricalBlock = BlockType.BEACON_LIT.ordinal();
        for (int y = 0; y < Chunk.SY; y++) {
            for (int z = 0; z < Chunk.SZ; z++) {
                for (int x = 0; x < Chunk.SX; x++) {
                    assertTrue(chunk.get(x, y, z).ordinal() <= lastHistoricalBlock,
                            "generator v1 emitted a post-0.2.0 block at " + x + "," + y + "," + z);
                }
            }
        }
    }
}
